# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: yaml-lint
on: [ "push", "pull_request" ]
jobs:
  yaml-lint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
